application: postbin1
version: 1
runtime: python
api_version: 1

handlers:
- url: /
  script: main.py
- url: /(.*\.(gif|png|jpg|ico))
  static_files: static/\1
  upload: static/(.*\.(gif|png|jpg|ico))
- url: /static
  static_dir: static
- url: /.*
  script: bin.py